const SHOP_DATA = [
  {
    id: 1,
    title: 'Sega',
    routeName: 'sega',
    items: [
      {
        id: 1,
        name: 'Crazy Taxi',
        imageUrl: '/sega/cover_01',
        price: 249,
      },
      {
        id: 2,
        name: 'The King of Fighters Evolution',
        imageUrl: '/sega/cover_02',
        price: 249,
      },
      {
        id: 3,
        name: 'Mortal Kombat',
        imageUrl: '/sega/cover_03',
        price: 249,
      },
      {
        id: 4,
        name: 'Sonic CD',
        imageUrl: '/sega/cover_04',
        price: 249,
      },
      {
        id: 5,
        name: 'Mickey Mania',
        imageUrl: '/sega/cover_05',
        price: 249,
      },
      {
        id: 6,
        name: 'Flashback',
        imageUrl: '/sega/cover_06',
        price: 249,
      },
      {
        id: 7,
        name: 'Batman Returns',
        imageUrl: '/sega/cover_07',
        price: 249,
      },
      {
        id: 8,
        name: 'Gauntlet',
        imageUrl: '/sega/cover_08',
        price: 249,
      },
      {
        id: 9,
        name: 'Quake',
        imageUrl: '/sega/cover_09',
        price: 249,
      },
      {
        id: 10,
        name: 'Sonic The Hedgehog',
        imageUrl: '/sega/cover_10',
        price: 249,
      },
      {
        id: 11,
        name: 'Streets of Rage 2',
        imageUrl: '/sega/cover_11',
        price: 249,
      },
      {
        id: 12,
        name: 'Altered Beast',
        imageUrl: '/sega/cover_12',
        price: 249,
      },
      {
        id: 13,
        name: 'Virtua Fighter',
        imageUrl: '/sega/cover_13',
        price: 249,
      },
      {
        id: 14,
        name: 'Virtua Tennis',
        imageUrl: '/sega/cover_14',
        price: 249,
      },
      {
        id: 15,
        name: 'Resident Evil 2',
        imageUrl: '/sega/cover_15',
        price: 249,
      },
      {
        id: 16,
        name: 'Aladdin',
        imageUrl: '/sega/cover_16',
        price: 249,
      },
    ],
  },
  {
    id: 2,
    title: 'Xbox',
    routeName: 'xbox',
    items: [
      {
        id: 1,
        name: 'Dance Central 3',
        imageUrl: '/xbox/cover_01',
        price: 249,
      },
      {
        id: 2,
        name: 'Deadrising 2',
        imageUrl: '/xbox/cover_02',
        price: 249,
      },
      {
        id: 3,
        name: 'Dragon Ball Z',
        imageUrl: '/xbox/cover_03',
        price: 249,
      },
      {
        id: 4,
        name: 'Fallout 3',
        imageUrl: '/xbox/cover_04',
        price: 249,
      },
      {
        id: 5,
        name: 'Forza Motorsport 3',
        imageUrl: '/xbox/cover_05',
        price: 249,
      },
      {
        id: 6,
        name: 'Gears of War 2',
        imageUrl: '/xbox/cover_06',
        price: 249,
      },
      {
        id: 7,
        name: 'Mass Efect',
        imageUrl: '/xbox/cover_07',
        price: 249,
      },
      {
        id: 8,
        name: 'Phantasy Star Universe',
        imageUrl: '/xbox/cover_08',
        price: 249,
      },
      {
        id: 9,
        name: 'Skyrim',
        imageUrl: '/xbox/cover_09',
        price: 249,
      },
    ],
  },
  {
    id: 3,
    title: 'Nintendo',
    routeName: 'nintendo',
    items: [
      {
        id: 1,
        name: 'Donkey Kong Country 3',
        imageUrl: '/nintendo/cover_01',
        price: 249,
      },
      {
        id: 2,
        name: 'Killer Instinc',
        imageUrl: '/nintendo/cover_02',
        price: 249,
      },
      {
        id: 3,
        name: 'Mortal Kombat 2',
        imageUrl: '/nintendo/cover_02',
        price: 249,
      },
      {
        id: 4,
        name: 'Super Mario All Stars',
        imageUrl: '/nintendo/cover_04',
        price: 249,
      },
      {
        id: 5,
        name: 'Super Metroid',
        imageUrl: '/nintendo/cover_05',
        price: 249,
      },
      {
        id: 6,
        name: 'The Legend of Zelda',
        imageUrl: '/nintendo/cover_06',
        price: 249,
      },
      {
        id: 7,
        name: 'Super Mario 64',
        imageUrl: '/nintendo/cover_07',
        price: 249,
      },
      {
        id: 8,
        name: 'Quake 64',
        imageUrl: '/nintendo/cover_08',
        price: 249,
      },
      {
        id: 9,
        name: 'Pokemon Stadium',
        imageUrl: '/nintendo/cover_09',
        price: 249,
      },
      {
        id: 10,
        name: 'Mario Kart 64',
        imageUrl: '/nintendo/cover_10',
        price: 249,
      },
      {
        id: 11,
        name: 'Forsaken 64',
        imageUrl: '/nintendo/cover_11',
        price: 249,
      },
      {
        id: 12,
        name: 'Donkey Kong 64',
        imageUrl: '/nintendo/cover_12',
        price: 249,
      },
      {
        id: 13,
        name: 'Castlevania',
        imageUrl: '/nintendo/cover_13',
        price: 249,
      },
      {
        id: 14,
        name: 'Contra',
        imageUrl: '/nintendo/cover_14',
        price: 249,
      },
      {
        id: 15,
        name: 'The Legend of Zelda',
        imageUrl: '/nintendo/cover_15',
        price: 249,
      },
      {
        id: 16,
        name: 'Super Mario Bros 2',
        imageUrl: '/nintendo/cover_16',
        price: 249,
      },
      {
        id: 17,
        name: 'Super Mario Bros 3',
        imageUrl: '/nintendo/cover_17',
        price: 249,
      },
      {
        id: 18,
        name: 'Tetris',
        imageUrl: '/nintendo/cover_18',
        price: 249,
      },
    ],
  },
  {
    id: 4,
    title: 'Playstation',
    routeName: 'playstation',
    items: [
      {
        id: 1,
        name: 'God of War',
        imageUrl: '/playstation/cover_01',
        price: 249,
      },
      {
        id: 2,
        name: 'The Last of Us Remastered',
        imageUrl: '/playstation/cover_02',
        price: 249,
      },
      {
        id: 3,
        name: 'Resident Evil 4',
        imageUrl: '/playstation/cover_03',
        price: 249,
      },
      {
        id: 4,
        name: 'Horizon Zero Down',
        imageUrl: '/playstation/cover_04',
        price: 249,
      },
      {
        id: 5,
        name: 'Uncharted 4',
        imageUrl: '/playstation/cover_05',
        price: 249,
      },
      {
        id: 6,
        name: 'Until Down',
        imageUrl: '/playstation/cover_06',
        price: 249,
      },
      {
        id: 7,
        name: 'Skyrim',
        imageUrl: '/playstation/cover_07',
        price: 249,
      },
      {
        id: 8,
        name: 'Unreal Tournament',
        imageUrl: '/playstation/cover_08',
        price: 249,
      },
      {
        id: 9,
        name: 'Splinter Cell Blacklist',
        imageUrl: '/playstation/cover_09',
        price: 249,
      },
      {
        id: 10,
        name: 'Bioshock 2',
        imageUrl: '/playstation/cover_10',
        price: 249,
      },
      {
        id: 11,
        name: 'Dark Souls',
        imageUrl: '/playstation/cover_11',
        price: 249,
      },
      {
        id: 12,
        name: 'Fallout New Vegas',
        imageUrl: '/playstation/cover_12',
        price: 249,
      },
      {
        id: 13,
        name: 'Killzone',
        imageUrl: '/playstation/cover_13',
        price: 249,
      },
      {
        id: 14,
        name: 'Tomb Raider Legend',
        imageUrl: '/playstation/cover_14',
        price: 249,
      },
      {
        id: 15,
        name: 'Monster Hunter',
        imageUrl: '/playstation/cover_15',
        price: 249,
      },
      {
        id: 16,
        name: 'Resident Evil 4',
        imageUrl: '/playstation/cover_16',
        price: 249,
      },
      {
        id: 17,
        name: 'Resident Evil 2',
        imageUrl: '/playstation/cover_17',
        price: 249,
      },
      {
        id: 18,
        name: 'Resident Evil 3',
        imageUrl: '/playstation/cover_18',
        price: 249,
      },
      {
        id: 19,
        name: 'Silent Hill',
        imageUrl: '/playstation/cover_19',
        price: 249,
      },
      {
        id: 20,
        name: 'Tekken 3',
        imageUrl: '/playstation/cover_20',
        price: 249,
      },
      {
        id: 21,
        name: 'Crash Bandicoot',
        imageUrl: '/playstation/cover_21',
        price: 249,
      },
      {
        id: 22,
        name: 'Crash Team Racing',
        imageUrl: '/playstation/cover_22',
        price: 249,
      },
    ],
  },
  {
    id: 5,
    title: 'Atari',
    routeName: 'atari',
    items: [
      {
        id: 1,
        name: 'E.T. The Extra-Terrestrial',
        imageUrl: '/atari/cover_01',
        price: 2490,
      },
      {
        id: 2,
        name: 'Mario Bros',
        imageUrl: '/atari/cover_02',
        price: 249,
      },
      {
        id: 3,
        name: 'Ms. Pac-Man',
        imageUrl: '/atari/cover_04',
        price: 249,
      },
      {
        id: 4,
        name: 'Star Wars The Empire Strikes Back',
        imageUrl: '/atari/cover_04',
        price: 249,
      },
      {
        id: 5,
        name: 'Asteroids',
        imageUrl: '/atari/cover_05',
        price: 249,
      },
      {
        id: 6,
        name: 'Commando',
        imageUrl: '/atari/cover_06',
        price: 249,
      },
      {
        id: 7,
        name: 'Donkey Kong',
        imageUrl: '/atari/cover_07',
        price: 249,
      },
      {
        id: 8,
        name: 'Alien vs Predator',
        imageUrl: '/atari/cover_08',
        price: 249,
      },
      {
        id: 9,
        name: 'Cannon Fodder',
        imageUrl: '/atari/cover_09',
        price: 249,
      },
      {
        id: 10,
        name: 'Doom',
        imageUrl: '/atari/cover_10',
        price: 249,
      },
      {
        id: 11,
        name: 'Double Dragon',
        imageUrl: '/atari/cover_11',
        price: 249,
      },
    ],
  },
];

export default SHOP_DATA;
